# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{guise}
  s.version = "1.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Kirk (Modulus 7, LLC)"]
  s.date = %q{2011-06-07}
  s.description = %q{Guise is the SVM driven sentiment engine for SocialVolt}
  s.email = %q{matt@matthewkirk.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".autotest",
    ".document",
    ".rspec",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "data/dictionary.txt",
    "data/negative_words.txt",
    "data/output.yml",
    "data/positive_words.txt",
    "data/stopwords.txt",
    "guise.gemspec",
    "lib/guise.rb",
    "lib/guise/bit_field.rb",
    "lib/guise/bloominsimple.rb",
    "lib/guise/config.rb",
    "lib/guise/cross_validation.rb",
    "lib/guise/trainer.rb",
    "lib/guise/uri_strip.rb",
    "spec/guise_spec.rb",
    "spec/spec_helper.rb",
    "spec/trainer_spec.rb"
  ]
  s.homepage = %q{http://github.com/hexgnu/guise}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{Guise is the SVM driven sentiment engine for SocialVolt}
  s.test_files = [
    "spec/guise_spec.rb",
    "spec/spec_helper.rb",
    "spec/trainer_spec.rb"
  ]
  s.add_dependency(%q<hexgnu-libsvm-ruby-swig>, ["= 0.1.3.1"])
  s.add_development_dependency("rspec")
end

